# Generated by Django 2.1.7 on 2019-03-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190319_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['commented_at']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='commented_by',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Enter comment about post here.', max_length=2000),
        ),
    ]
